use std::env::{self, var};

fn main() {
  // Don't rerun this on changes other than build.rs, as we only depend on
  // the rustc version.
  println!("cargo:rerun-if-changed=build.rs");

  // Check for `--features=tarpaulin`.
  let tarpaulin = var("CARGO_FEATURE_TARPAULIN").is_ok();

  if tarpaulin {
    use_feature("tarpaulin");
  } else {
    // Always rerun if these env vars change.
    println!("cargo:rerun-if-env-changed=CARGO_TARPAULIN");
    println!("cargo:rerun-if-env-changed=CARGO_CFG_TARPAULIN");

    // Detect tarpaulin by environment variable
    if env::var("CARGO_TARPAULIN").is_ok() || env::var("CARGO_CFG_TARPAULIN").is_ok() {
      use_feature("tarpaulin");
    }
  }

  // Rerun this script if any of our features or configuration flags change,
  // or if the toolchain we used for feature detection changes.
  println!("cargo:rerun-if-env-changed=CARGO_FEATURE_TARPAULIN");

  // Bundled-calibration codegen: parse `models/siglip2/calibration.json`
  // and emit `BUNDLED_LOGIT_SCALE` / `BUNDLED_LOGIT_BIAS` constants to
  // `$OUT_DIR/bundled_calibration.rs`, which `src/calibration.rs`
  // includes under `#[cfg(feature = "bundled")]`. Only runs when the
  // `bundled` feature is active so non-bundled builds skip both the
  // file read and the (tiny) serde_json parse cost.
  //
  // The generated file is OUT_DIR-only — never written to the source
  // tree — so this is a pure build-output, not a checked-in artifact.
  // Re-runs are gated on the JSON file's mtime so warm builds skip
  // entirely.
  if env::var_os("CARGO_FEATURE_BUNDLED").is_some() {
    generate_bundled_calibration();
  }
  // Always declare the rerun trigger so disabling and re-enabling
  // `bundled` invalidates the cached artifact appropriately.
  println!("cargo:rerun-if-env-changed=CARGO_FEATURE_BUNDLED");
}

fn use_feature(feature: &str) {
  println!("cargo:rustc-cfg={}", feature);
}

#[derive(serde::Deserialize)]
struct CalibrationJson {
  logit_scale: f32,
  logit_bias: f32,
}

fn generate_bundled_calibration() {
  const SOURCE: &str = "models/siglip2/calibration.json";
  println!("cargo:rerun-if-changed={SOURCE}");

  let bytes = std::fs::read(SOURCE).unwrap_or_else(|err| panic!("read {SOURCE}: {err}"));
  let parsed: CalibrationJson =
    serde_json::from_slice(&bytes).unwrap_or_else(|err| panic!("parse {SOURCE}: {err}"));

  // Sanity-check the values fall inside `Calibration::SCALE_MIN..=SCALE_MAX`
  // (-10..=8) and `|bias| <= BIAS_ABS_MAX` (50). Catches a bad JSON commit
  // at build time rather than at first `Calibration::bundled()` call.
  // Mirrors the runtime `Calibration::validate` invariants — kept in
  // lock-step manually since we can't import the crate from its own
  // build script.
  if !parsed.logit_scale.is_finite() || !(-10.0..=8.0).contains(&parsed.logit_scale) {
    panic!(
      "{SOURCE}: logit_scale = {} outside operational range [-10, 8]",
      parsed.logit_scale
    );
  }
  if !parsed.logit_bias.is_finite() || parsed.logit_bias.abs() > 50.0 {
    panic!(
      "{SOURCE}: logit_bias = {} outside operational range |x| <= 50",
      parsed.logit_bias
    );
  }

  let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
  let out_path = std::path::PathBuf::from(out_dir).join("bundled_calibration.rs");
  // `{:?}` for f32 / f64 emits a shortest-decimal representation that
  // round-trips back to the same bit pattern, so the generated literal
  // is bit-exact with the parsed value despite going through text.
  let contents = format!(
    "// Auto-generated by build.rs from `{SOURCE}`. Do not edit.\n\
     pub(crate) const BUNDLED_LOGIT_SCALE: f32 = {scale:?}_f32;\n\
     pub(crate) const BUNDLED_LOGIT_BIAS: f32 = {bias:?}_f32;\n",
    scale = parsed.logit_scale,
    bias = parsed.logit_bias,
  );
  std::fs::write(&out_path, contents)
    .unwrap_or_else(|err| panic!("write {}: {err}", out_path.display()));
}
